package safedns

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"sync"
)

// SafeDNSManager 管理 SafeSearch 与域名拦截
type SafeDNSManager struct {
	mu             sync.Mutex
	confPath       string
	enableSafeSrch bool
	blockAdult     bool
	customBlack    []string
	customWhite    []string
}

// NewSafeDNSManager 创建 DNS 管理器
func NewSafeDNSManager(confPath string) *SafeDNSManager {
	if confPath == "" {
		confPath = "/tmp/dnsmasq.d/parentcontrol.conf"
	}
	return &SafeDNSManager{
		confPath:       confPath,
		enableSafeSrch: true,
		blockAdult:     true,
		customBlack:    make([]string, 0),
		customWhite:    make([]string, 0),
	}
}

// ApplyConfig 更新并重新生成 dnsmasq 规则配置
func (sd *SafeDNSManager) ApplyConfig(safeSearch, blockAdult bool, blackList, whiteList []string) error {
	sd.mu.Lock()
	defer sd.mu.Unlock()

	sd.enableSafeSrch = safeSearch
	sd.blockAdult = blockAdult
	sd.customBlack = blackList
	sd.customWhite = whiteList

	var sb strings.Builder
	sb.WriteString("# Generated by ParentControl. DO NOT EDIT MANUALLY.\n\n")

	// 1. 强制 SafeSearch
	if sd.enableSafeSrch {
		sb.WriteString("# === SafeSearch Enforcement ===\n")
		// Google SafeSearch (forcesafesearch.google.com: 216.239.38.120)
		sb.WriteString("address=/www.google.com/forcesafesearch.google.com\n")
		sb.WriteString("address=/www.google.com.hk/forcesafesearch.google.com\n")
		sb.WriteString("address=/google.com/216.239.38.120\n")
		sb.WriteString("address=/www.google.com/216.239.38.120\n")

		// Bing SafeSearch (strict.bing.com: 204.79.197.220)
		sb.WriteString("address=/www.bing.com/204.79.197.220\n")
		sb.WriteString("address=/cn.bing.com/204.79.197.220\n")
		sb.WriteString("address=/bing.com/204.79.197.220\n")

		// YouTube Restricted Mode (restrict.youtube.com: 216.239.38.119)
		sb.WriteString("address=/www.youtube.com/216.239.38.119\n")
		sb.WriteString("address=/m.youtube.com/216.239.38.119\n")
		sb.WriteString("address=/youtubei.googleapis.com/216.239.38.119\n")
		sb.WriteString("address=/youtube.googleapis.com/216.239.38.119\n")
		sb.WriteString("address=/www.youtube-nocookie.com/216.239.38.119\n\n")
	}

	// 2. 常见成人/有害网站阻断
	if sd.blockAdult {
		sb.WriteString("# === Adult and Dangerous Sites Filter ===\n")
		adultDomains := []string{
			"pornhub.com", "xvideos.com", "xnxx.com", "xhamster.com",
			"youporn.com", "redtube.com", "chaturbate.com", "stripchat.com",
			"livejasmin.com", "bonga.com", "cam4.com", "spankbang.com",
			"tube8.com", "beeg.com", "tnaflix.com", "eporner.com",
		}
		for _, domain := range adultDomains {
			sb.WriteString(fmt.Sprintf("address=/%s/0.0.0.0\n", domain))
		}
		sb.WriteString("\n")
	}

	// 3. 自定义黑名单
	if len(sd.customBlack) > 0 {
		sb.WriteString("# === Custom Blacklist ===\n")
		for _, domain := range sd.customBlack {
			domain = strings.TrimSpace(domain)
			if domain != "" {
				sb.WriteString(fmt.Sprintf("address=/%s/0.0.0.0\n", domain))
			}
		}
		sb.WriteString("\n")
	}

	// 确保目标目录存在
	_ = os.MkdirAll("/tmp/dnsmasq.d", 0755)

	if err := os.WriteFile(sd.confPath, []byte(sb.String()), 0644); err != nil {
		log.Printf("[SafeDNS] Failed to write dnsmasq config to %s: %v", sd.confPath, err)
		return err
	}

	// 热重载 dnsmasq
	if err := exec.Command("killall", "-HUP", "dnsmasq").Run(); err != nil {
		_ = exec.Command("/etc/init.d/dnsmasq", "reload").Run()
	}

	log.Printf("[SafeDNS] Applied DNS rules to %s and reloaded dnsmasq.", sd.confPath)
	return nil
}

// Cleanup 清理 DNS 配置文件并重载 dnsmasq
func (sd *SafeDNSManager) Cleanup() {
	sd.mu.Lock()
	defer sd.mu.Unlock()

	_ = os.Remove(sd.confPath)
	_ = exec.Command("killall", "-HUP", "dnsmasq").Run()
	log.Println("[SafeDNS] Removed dnsmasq parent control rules.")
}
